# fly.toml app configuration file generated for vinyljunkies-twitch-bot on 2025-04-19T16:26:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vinyljunkies-twitch-bot'
primary_region = 'fra'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate"

# Ensure the app keeps running and doesn't get automatically stopped
[processes]
  app = "node dist/index.js"
