# fly.toml app configuration file generated for vinyljunkies-twitch-bot on 2025-04-19T20:57:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vinyljunkies-twitch-bot'
primary_region = 'arn'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[scale]]
  count = 1

[[services]]

[[restart]]
  policy = "never"
  retries = 1
